//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventPlanner_
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventOrder
    {
        public int EventID { get; set; }
        public string EventType { get; set; }
        public string DateOfEvent { get; set; }
        public string Venue { get; set; }
        public string NoOfGuest { get; set; }
    }
}
