//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web;
namespace EventPlanner_
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

	public partial class igm
	{
		public int Id { get; set; }
		[DisplayName("")]
		public string ImagePath { get; set; }
	}
}
