//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GemDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GemDBEntities : DbContext
    {
        public GemDBEntities()
            : base("name=GemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Directors> Directors { get; set; }
        public virtual DbSet<EventManager> EventManager { get; set; }
        public virtual DbSet<OrderEvents> OrderEvents { get; set; }
        public virtual DbSet<OrganizeEvents> OrganizeEvents { get; set; }
        public virtual DbSet<Photographers> Photographers { get; set; }
        public virtual DbSet<Vanues> Vanues { get; set; }
    }
}
