//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GemDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderEvents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderEvents()
        {
			var ensureDLLIsCopied =
				System.Data.Entity.SqlServer.SqlProviderServices.Instance;
			this.OrganizeEvents = new HashSet<OrganizeEvents>();
        }
    
        public int EventID { get; set; }
        public int ClientID { get; set; }
        public string EventType { get; set; }
        public System.DateTime DateOfEvent { get; set; }
        public Nullable<System.TimeSpan> TimeOfEvent { get; set; }
        public int NoOfGuest { get; set; }
        public Nullable<int> V_ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public int EM_Fee { get; set; }
        public int CateringCost { get; set; }
        public int TotalCost { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Photographers Photographers { get; set; }
        public virtual Vanues Vanues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizeEvents> OrganizeEvents { get; set; }
    }
}
