//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GemDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizeEvents
    {
        public int EventID { get; set; }
        public int EM_ID { get; set; }
        public string EventStatus { get; set; }
        public string PaymentStatus { get; set; }
    
        public virtual EventManager EventManager { get; set; }
        public virtual OrderEvents OrderEvents { get; set; }
    }
}
