//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GemDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photographers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Photographers()
        {
            this.OrderEvents = new HashSet<OrderEvents>();
        }
    
        public int P_ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public int Fee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderEvents> OrderEvents { get; set; }
    }
}
